// Offline sanity check for the map generator.
//   node tools/mapcheck.js [seedCount] [players]
// Prints an ASCII preview of the first map plus connectivity and fairness
// stats for the rest. Water is impassable, so the thing worth checking is that
// the lakes and rivers never cut a base off from the fight.
//
// Pass a player count to check the two- and three-seat layouts; with none it
// sweeps all three, because the shapes are generated by one rule and a change
// that helps four players can easily ruin two.
import { generateMap, canStep } from '../src/game/mapgen.js';
import { LEVEL } from '../src/game/consts.js';

const N4 = [[1, 0], [-1, 0], [0, 1], [0, -1]];

function reachableFrom(map, sx, sy) {
  const t = map.tiles;
  const idx = (x, y) => y * t + x;
  const seen = new Uint8Array(map.level.length);
  const q = [idx(sx, sy)];
  seen[q[0]] = 1;
  for (let h = 0; h < q.length; h++) {
    const i = q[h];
    const tx = i % t, ty = (i / t) | 0;
    for (const [ox, oy] of N4) {
      const nx = tx + ox, ny = ty + oy;
      if (nx < 0 || ny < 0 || nx >= t || ny >= t) continue;
      const j = idx(nx, ny);
      if (seen[j] || !canStep(map.level, i, j)) continue;
      seen[j] = 1; q.push(j);
    }
  }
  return seen;
}

const count = Number(process.argv[2] || 8);
const only = process.argv[3] ? Number(process.argv[3]) : null;
const seatCounts = only ? [only] : [2, 3, 4];
let failures = 0;

for (const players of seatCounts) {
  console.log(`\n=== ${players} players ===`);
  let shown = false;

  for (let s = 0; s < count; s++) {
    const seed = 1000 + s * 7919;
    const t0 = Date.now();
    const map = generateMap(seed, players);
    const ms = Date.now() - t0;
    const t = map.tiles;
    const idx = (x, y) => y * t + x;

    const reach = reachableFrom(map, map.starts[0].tx, map.starts[0].ty);
    const startsOk = map.starts.every((p) => reach[idx(p.tx, p.ty)]);
    if (!startsOk || map.starts.length !== players) failures++;

    let water = 0, land = 0, landReach = 0;
    for (let i = 0; i < map.level.length; i++) {
      if (map.level[i] === LEVEL.WATER) { water++; continue; }
      land++;
      if (reach[i]) landReach++;
    }
    const byKind = { wood: 0, gold: 0 };
    for (const n of map.nodes) byKind[n.kind]++;

    // Per-seat fairness: nodes within 12 tiles of each base.
    const near = map.starts.map((p) => {
      const c = { wood: 0, gold: 0 };
      for (const n of map.nodes) {
        if ((n.tx - p.tx) ** 2 + (n.ty - p.ty) ** 2 <= 144) c[n.kind]++;
      }
      return `${c.wood}w/${c.gold}g`;
    });

    console.log(
      `seed ${seed}  ${t}x${t}  ${ms}ms  starts=${startsOk ? 'OK ' : 'FAIL'}  ` +
      `land=${((land / (t * t)) * 100).toFixed(0)}% reachable=${landReach}/${land} ` +
      `nodes=${map.nodes.length} (${byKind.wood}w ${byKind.gold}g) ` +
      `near=[${near.join(' ')}]`);

    if (!shown) {
      shown = true;
      const nodeAt = new Map();
      for (const n of map.nodes) nodeAt.set(idx(n.tx, n.ty), n.kind[0].toUpperCase());
      let out = '';
      for (let y = 0; y < t; y++) {
        for (let x = 0; x < t; x++) {
          const i = idx(x, y);
          const isBase = map.starts.some((p) => Math.abs(p.tx - x) < 2 && Math.abs(p.ty - y) < 2);
          if (isBase) out += '@';
          else if (nodeAt.has(i)) out += nodeAt.get(i);
          else if (map.level[i] === LEVEL.WATER) out += '~';
          else if (!reach[i]) out += '!';        // land no base can walk to
          else out += '.';
        }
        out += '\n';
      }
      console.log(out);
    }
  }
}

if (failures) {
  console.error(`\n${failures} map(s) failed the connectivity or seat-count check`);
  process.exit(1);
}
console.log('\nall maps connected, every seat placed');
